apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: testmariadb
spec:
  selector:
    matchLabels:
      app: testmariadb
  template:
    metadata:
      labels:
        app: testmariadb
    spec:
      containers:
        - image: mariadb:11.7.2
          name: mariadb
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: "Password1!"
            - name: MARIADB_PASSWORD
              value: "Password1!"
            - name: MARIADB_USER
              value: "user"
            - name: MARIADB_DATABASE
              value: "test"
          volumeMounts:
            - name: mariadata
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadata
          persistentVolumeClaim:
            claimName: pv0003-volclaim
---
apiVersion: v1
kind: Service
metadata:
  name: testmariadb
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: testmariadb
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Mi
  hostPath:
    path: /data/pv0003/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv0003-volclaim
spec:
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
