apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: {{ .Release.Namespace }}
data:
  FLASK_APP: "/app"
  PGHOST: {{ .Values.db.host | quote }}
  PGPORT: {{ .Values.db.port | quote }}
  PGDATABASE: {{ .Values.db.name | quote }}
  PGUSER: {{ .Values.db.user | quote }}
  KEYCLOAK_URL: "http://keycloak.{{ include "kc_namespace" . }}.svc.cluster.local"
  DEFAULT_NAMESPACE: {{ .Release.Namespace }}
  KEYCLOAK_NAMESPACE: {{ include "kc_namespace" . }}
  TASK_NAMESPACE: {{ include "tasks_namespace" . }}
  CLEANUP_AFTER_DAYS: {{ .Values.cleanupTime | quote }}
  PUBLIC_URL: {{ .Values.host }}
  RESULTS_PATH: {{ .Values.federatedNode.volumes.results_path }}
  TASK_POD_RESULTS_PATH: {{ .Values.federatedNode.volumes.task_pod_results_path }}
  IMAGE_TAG: {{ include "image-tag" . }}
{{ if .Values.storage.azure }}
  AZURE_STORAGE_ENABLED: "true"
  AZURE_SHARE_NAME: {{ .Values.storage.azure.shareName }}/results
  AZURE_SECRET_NAME: {{ .Values.storage.azure.secretName | default "azure-storage-secret" }}
{{ end }}
