{{- $db_pass := .Values.db.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
    PGPASSWORD: {{ $db_pass | b64enc | quote }}
