apiVersion: batch/v1
kind: CronJob
metadata:
  name: result-cleaner
spec:
  schedule: "0 12 * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 60
      template:
        spec:
          containers:
          - name: result-cleaner
            image: alpine:3.19
            imagePullPolicy: IfNotPresent
            env:
            - name: RESULTS_PATH
              value: {{ .Values.federatedNode.volumes.results_path }}
            - name: CLEANUP_AFTER_DAYS
              value: "{{ .Values.cleanupTime }}"
            volumeMounts:
            - name: respv
              mountPath: {{ .Values.federatedNode.volumes.results_path }}
            command:
            - /bin/sh
            - -c
            - find ${RESULTS_PATH} -type d -mtime +${CLEANUP_AFTER_DAYS} -name '*' -print0 | xargs -r0 rm -r --
          restartPolicy: Never
          volumes:
          - name: respv
            persistentVolumeClaim:
              claimName: flask-results-pv-volclaim
