{{- define "crList" }}
{{- $content := dict -}}
  {{- range $v := .Values.registries -}}
    {{ if .secret }}
      {{ $sec := lookup "v1" "Secret" $.Release.Namespace .secret.name | default dict }}
      {{ if $sec }}
        {{ $username := (index $sec.data .secret.userKey) | b64dec | trim }}
        {{ $password := (index $sec.data .secret.passKey) | b64dec | trim }}
        {{ $content = merge $content (dict $v.url (dict "username" $username "password" $password "email" "" "auth" (printf "%s:%s" $username $password | b64enc))) }}
      {{ end }}
    {{- else }}
      {{ $content = merge $content (dict $v.url (dict "username" $v.username "password" $v.password "email" $v.email "auth" (printf "%s:%s" $v.username $v.password | b64enc))) }}
    {{- end }}
  {{- end }}
  registries-list.json: {{ $content | toJson | b64enc | quote }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: backend-cr-config-secret
  namespace: {{ .Release.Namespace }}
data:
  {{ template "crList" . }}
