apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: {{ .Release.Namespace }}
data:
  FLASK_APP: "/app"
  PGHOST: {{ .Values.db.host | quote }}
  PGPORT: {{ .Values.db.port | quote }}
  PGDATABASE: {{ .Values.db.name | quote }}
  PGUSER: {{ .Values.db.user | quote }}
  KEYCLOAK_URL: "http://keycloak.{{ .Values.namespaces.keycloak }}.svc.cluster.local"
  DEFAULT_NAMESPACE: {{ .Release.Namespace }}
  KEYCLOAK_NAMESPACE: {{ .Values.namespaces.keycloak }}
  TASK_NAMESPACE: {{ .Values.namespaces.tasks }}
  CLEANUP_AFTER_DAYS: {{ .Values.cleanupTime | quote }}
  PUBLIC_URL: {{ .Values.ingress.host }}
{{ if .Values.storage.azure }}
  AZURE_STORAGE_ENABLED: "true"
  AZURE_SHARE_NAME: {{ .Values.storage.azure.shareName }}/results
  AZURE_SECRET_NAME: {{ .Values.storage.azure.secretName | default "azure-storage-secret" }}
{{ end }}
