apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: {{ .Release.Namespace }}
data:
  FLASK_APP: "/app"
  PGHOST: {{ .Values.db.host | default "db" | quote }}
  PGPORT: {{ .Values.db.port | default "5432" | quote }}
  PGDATABASE: {{ .Values.db.name | default "fndb" | quote }}
  PGUSER: {{ .Values.db.user | default "admin" | quote }}
  KEYCLOAK_URL: "https://{{ .Values.ingress.host }}/keycloak"
  DEFAULT_NAMESPACE: {{ .Release.Namespace }}
  KEYCLOAK_NAMESPACE: {{ .Values.namespaces.keycloak }}
  TASK_NAMESPACE: {{ .Values.namespaces.tasks }}
  CLEANUP_AFTER_DAYS: {{ .Values.cleanupTime | quote }}
{{ if .Values.local_development }}
  VERIFY_SSL: "false"
{{ end }}
{{ if .Values.storage.azure }}
  AZURE_STORAGE_ENABLED: "true"
  AZURE_SHARE_NAME: {{ .Values.storage.azure.shareName }}/results
  AZURE_SECRET_NAME: {{ .Values.storage.azure.secretName | default "azure-storage-secret" }}
{{ end }}
