## This assumes for certain secrets to be present in the release namespace
# Basically duplicates them to the keycloak's namespace
{{- range list .Values.db.secret.name }}
{{- with include "lookupOrError" (dict "entity" "Secret" "namespace" $.Release.Namespace "name" .) | fromYaml }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .metadata.name }}
  namespace: {{ include "kc_namespace" $ }}
data:
{{ toYaml .data | indent 2 }}
type: {{ .type }}
{{- end }}
---
{{- end }}
## This is optional
{{ if (.Values.firstUserSecret).name }}
{{- with include "lookupOrError" (dict "entity" "Secret" "namespace" $.Release.Namespace "name" (.Values.firstUserSecret).name) | fromYaml }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .metadata.name }}
  namespace: {{ include "kc_namespace" $ }}
data:
{{ toYaml .data | indent 2 }}
type: {{ .type }}
{{- end }}
---
{{- end }}
{{- if .Values.storage.azure }}
{{- with include "lookupOrError" (dict "entity" "Secret" "namespace" $.Release.Namespace "name" .Values.storage.azure.secretName) | fromYaml }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .metadata.name }}
  namespace: {{ include "tasks_namespace" $ }}
data:
{{ toYaml .data | indent 2 }}
type: {{ .type}}
{{- end }}
---
{{- end }}
{{- if and (index .Values "cert-manager" "enabled") .Values.on_aks }}
{{- with include "lookupOrError" (dict "entity" "Secret" "namespace" $.Release.Namespace "name" .Values.certs.azure.secretName) | fromYaml }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .metadata.name }}
  namespace: {{ (index $.Values "cert-manager" "namespace") }}
data:
{{ toYaml .data | indent 2 }}
type: {{ .type }}
{{- end }}
---
{{- end }}
{{- if and (index .Values "cert-manager" "enabled") .Values.on_eks }}
{{- with include "lookupOrError" (dict "entity" "Secret" "namespace" $.Release.Namespace "name" .Values.certs.aws) | fromYaml }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .metadata.name }}
  namespace: {{ (index $.Values "cert-manager" "namespace") }}
data:
{{ toYaml .data | indent 2 }}
type: {{ .type }}
{{- end }}
---
{{- end }}
