apiVersion: v1
kind: PersistentVolume
metadata:
  name: dagster-artifacts-pv
spec:
  capacity:
    storage: {{ .Values.storage.capacity }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  {{ if .Values.storage.local }}
  local:
    path: {{ .Values.storage.local.artifacts }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - fn-control-plane
  {{ else if .Values.storage.azure }}
  azureFile:
    shareName: {{ .Values.storage.azure.shareName }}
    readOnly: false
    secretName: {{ .Values.storage.azure.secretName | default "azure-storage-secret" }}
  {{ else if .Values.storage.aws }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ include "awsStorageAccount" . }}
  {{ else if .Values.storage.nfs }}
  nfs:
    server: {{ .Values.storage.nfs.url }}
    path: {{ .Values.storage.nfs.path }}
    readOnly: false
  {{ end }}


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artifacts-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: ""
  volumeName: dagster-artifacts-pv
  resources:
    requests:
      storage: {{ .Values.storage.capacity }}
  accessModes:
    - ReadWriteOnce

