{{ if and (not .Values.db.secret) (not .Values.db.configMap) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-internal
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres:13-alpine
          name: db-internal
          env:
            - name: POSTGRES_DB
              value: {{ .Values.db.name | default "fndb" | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.db.user | default "admin" | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.db.password | quote }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: db-volclaim
{{ end }}
