{{- range list .Release.Namespace .Values.namespaces.keycloak }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-initializer-configmap
  namespace: {{ . }}
data:
  dbinit.sh: |-
    apk --update add postgresql-client
    psql -d postgres -U $PGUSER -tc "SELECT 1 FROM pg_database WHERE datname = '$NEW_DB'" | \
    grep -q 1 || psql -d postgres -U $PGUSER -c "CREATE DATABASE $NEW_DB"
---
{{- end }}
