{{ if and (not .Values.db.secret) (not .Values.db.configMap) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
spec:
  storageClassName: db-storage
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  # This should be changed to some more reliable destination
  {{ if .Values.storage.local }}
  local:
    path: {{ .Values.storage.local.dbpath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/os
          operator: In
          values:
          - linux
  {{ else if .Values.storage.azure }}
  azureFile:
    shareName: {{ .Values.storage.azure.shareName }}/db
    readOnly: false
    secretName: {{ .Values.storage.azure.secretName | default "azure-storage-secret" }}
  mountOptions:
  - dir_mode=0750
  - file_mode=0750
  - uid=70
  - gid=70
  - mfsymlinks
  - nobrl
  {{ else if .Values.storage.nfs }}
  {{ end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-volclaim
  namespace: {{ .Release.namespace }}
spec:
  storageClassName: db-storage
  # This should be changed to some more reliable destination
  volumeName: db-pv
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteMany
{{ end }}
