{{ if .Values.create_db_deployment }}
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "-2"
spec:
  ports:
    - port: 5432
      name: pgport
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres
{{ end }}
