apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-realm-init
  namespace: {{ include "kc_namespace" . }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-1"
    {{ template "defaultAnnotations" . }}
spec:
  ttlSecondsAfterFinished: 30
  template:
    metadata:
      name: "{{.Release.Name}}"
    spec:
      restartPolicy: Never
      containers:
        - name: post-install-job
          imagePullPolicy: {{ .Values.pullPolicy }}
          image: "ghcr.io/aridhia-open-source/keycloak_initializer:{{ .Values.keycloak.tag | default .Chart.AppVersion }}"
          {{ include "nonRootSC" . }}
          env:
            - name: KC_NAMESPACE
              value: {{ include "kc_namespace" . }}
            - name: KC_REPLICAS
              value: {{ .Values.keycloak.replicas | quote }}
          envFrom:
          - configMapRef:
              name: keycloak-config
          - secretRef:
              name: kc-secrets
