apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
  namespace: {{ include "kc_namespace" . }}
  labels:
    app: keycloak
spec:
  serviceName: keycloak-headless
  replicas: {{ .Values.keycloak.replicas | default 2 }}
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      annotations:
        fn.aridhia.com/credential-generation: {{ .Values.keycloak.credentialGeneration | default 1 | quote }}
        checksum/kc-config: {{ include (print $.Template.BasePath "/keycloak-configmap.yaml") . | sha256sum }}
      labels:
        app: keycloak
    spec:
      {{- if .Values.create_db_deployment }}
      initContainers:
        {{- include "pgWaitContainer" (dict "ctx" . "host" (include "dbKeycloakHost" . | trim) "port" (include "dbPort" .)) | nindent 8 }}
      {{- end }}
      containers:
        - image: {{ include "keycloak-image" . }}
          args: [
            "start",
            "--import-realm",
            "--http-enabled=true",
            "--optimized"
          ]
          name: keycloak
          imagePullPolicy: {{ .Values.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 9000
            initialDelaySeconds: 20
            periodSeconds: 10
          env:
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keycloak.db.secret.name }}
                  key: {{ .Values.keycloak.db.secret.key }}
          envFrom:
          - secretRef:
              name: kc-secrets
          - configMapRef:
              name: keycloak-config
          volumeMounts:
            - name: config
              mountPath: /opt/keycloak/data/import/
            - name: quarkus
              mountPath: /opt/keycloak/conf/quarkus.properties
              subPath: quarkus.properties
          {{- include "nonRootSC" . | nindent 10 }}
      volumes:
        - name: config
          configMap:
            name: keycloak-start-config
            items:
            - key: config.json
              path: config.json
        - name: quarkus
          configMap:
            name: keycloak-start-config
            items:
            - key: quarkus.properties
              path: quarkus.properties