apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: {{ include "kc_namespace" . }}
data:
  KEYCLOAK_ADMIN: admin
  KC_DB_URL_HOST: {{ .Values.db.host | default (print "db." .Release.Namespace ".svc.cluster.local") | quote }}
  KC_DB: postgres
  KC_DB_URL_PORT: {{ .Values.db.port | default "5432" | quote }}
  KC_DB_URL_DATABASE: fn_{{ .Values.db.name | default "kc_db" }}
  KC_DB_USERNAME: {{ .Values.db.user | default "admin" | quote }}
  KEYCLOAK_TOKEN_LIFE: {{ .Values.token.life | default 2592000 | quote }}
  KEYCLOAK_NAMESPACE: {{ include "kc_namespace" . }}
  KEYCLOAK_HOSTNAME: {{ .Values.ingress.host }}
  # PROXY_ADDRESS_FORWARDING: true
---
{{- $list_ns := list .Release.Namespace -}}
{{- if .Values.outbound -}}
    {{ $list_ns = append $list_ns .Values.global.namespaces.controller }}
{{- end -}}

{{- range $list_ns }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: {{ . }}
data:
  KEYCLOAK_ADMIN: admin
  KC_DB_URL_HOST: {{ $.Values.db.host | default (print "db." $.Release.Namespace ".svc.cluster.local") | quote }}
  KC_DB_USERNAME: {{ $.Values.db.user | default "admin" | quote }}
---
{{- end }}
