apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keycloak-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keycloak-role
subjects:
  - kind: ServiceAccount
    namespace: {{ include "kc_namespace" . }}
    name: k8s-keycloak-handler
roleRef:
  kind: ClusterRole
  name: keycloak-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-keycloak-handler
  namespace: {{ include "kc_namespace" . }}
