apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-realm-init
  namespace: {{ include "kc_namespace" . }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "-1"
    {{ template "defaultAnnotations" . }}
spec:
  template:
    metadata:
      name: "{{.Release.Name}}"
    spec:
      restartPolicy: Never
      containers:
        - name: post-install-job
          imagePullPolicy: {{ .Values.pullPolicy }}
          image: "ghcr.io/aridhia-open-source/keycloak_initializer:{{ .Values.keycloak.tag | default .Chart.AppVersion }}"
          {{ include "nonRootSC" . }}
          env:
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kc-secrets
                  key: KEYCLOAK_ADMIN_PASSWORD
            - name: KEYCLOAK_GLOBAL_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: kc-secrets
                  key: KEYCLOAK_GLOBAL_CLIENT_SECRET
            {{- if (.Values.firstUserSecret).name }}
            - name: FIRST_USER_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.firstUserSecret.name }}
                  key: {{ .Values.firstUserSecret.passKey }}
            - name: FIRST_USER_EMAIL
              value: {{ .Values.firstUserSecret.email }}
            - name: FIRST_USER_FIRST_NAME
              value: {{ .Values.firstUserSecret.firstName }}
            - name: FIRST_USER_LAST_NAME
              value: {{ .Values.firstUserSecret.lastName }}
            {{- end }}
          envFrom:
          - configMapRef:
              name: keycloak-config
