apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-credential-reset
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-upgrade,post-delete
    helm.sh/hook-delete-policy: hook-succeeded
    {{ template "defaultAnnotations" . }}
spec:
  ttlSecondsAfterFinished: 30
  template:
    metadata:
      name: "{{.Release.Name}}"
    spec:
      restartPolicy: Never
      containers:
        - name: post-install-job
          imagePullPolicy: {{ .Values.pullPolicy }}
          image: {{ include "fn-alpine" . }}
          command:
            - /bin/sh
            - -c
          args:
            - |
              psql -d fn_{{ .Values.db.name | default "kc_db" }} -U "$PGUSER" -f - <<SQL
                DELETE FROM credential WHERE user_id IN (SELECT user_id FROM user_entity WHERE username = 'admin');
                DELETE FROM user_role_mapping WHERE user_id IN (SELECT user_id FROM user_entity WHERE username = 'admin');
                DELETE FROM user_entity WHERE username = 'admin';
              SQL
          {{ include "nonRootSC" . }}
          env:
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: {{.Values.db.secret.name}}
                key: {{.Values.db.secret.key}}
          - name: PGHOST
            value: {{ .Values.db.host | default "db" | quote }}
          - name: PGPORT
            value: {{ .Values.db.port | default "5432" | quote }}
          - name: PGDATABASE
            value: {{ .Values.db.name | default "fndb" | quote }}
          - name: PGUSER
            value: {{ .Values.db.user | default "admin" | quote }}
