# This is not run if the secret kc-secret doesn't exist in keycloak's namespace
{{ $sec := (lookup "v1" "Secret" .Values.namespaces.keycloak "kc-secrets") }}
# Using .Release.IsUpgrade and the lookup to be compatible with argoCD and helm install/upgrade
{{ if or $sec .Release.IsUpgrade }}
apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-secrets-init
  namespace: {{ .Values.namespaces.keycloak }}
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-weight: "-3"
    helm.sh/hook-delete-policy: before-hook-creation
    {{ template "defaultAnnotations" . }}
spec:
  template:
    metadata:
      name: "{{.Release.Name}}"
    spec:
      restartPolicy: Never
      containers:
        - name: pre-kc-install-job
          image: "python:3.12.1-slim-bullseye"
          command: ["/bin/sh", "-c", "pip install requests && python3 /scripts/init_credentials.py" ]
          env:
            - name: KEYCLOAK_NAMESPACE
              value: {{ .Values.namespaces.keycloak }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kc-secrets
                  key: KEYCLOAK_ADMIN_PASSWORD
                  optional: true
            - name: KEYCLOAK_GLOBAL_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: kc-secrets
                  key: KEYCLOAK_GLOBAL_CLIENT_SECRET
                  optional: true
            - name: NEW_KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: new-kc-secrets
                  key: NEW_KEYCLOAK_ADMIN_PASSWORD
                  optional: true
            - name: NEW_KEYCLOAK_GLOBAL_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: new-kc-secrets
                  key: NEW_KEYCLOAK_GLOBAL_CLIENT_SECRET
          volumeMounts:
            - name: config
              mountPath: /scripts/
      volumes:
        - name: config
          configMap:
            name: keycloak-start-config
            items:
            - key: init_credentials.py
              path: init_credentials.py
{{ end }}
