apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-start-config
  namespace: {{ include "kc_namespace" . }}
  labels:
    {{ include "defaultLabels" . }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/resource-policy: keep
    {{ template "defaultAnnotations" . }}
data:
  config.json: |-
{{ .Files.Get "scripts/realms.json" | indent 4 }}
  quarkus.properties: |-
    quarkus.transaction-manager.enable-recovery=true
