{{- $client_secret := (include "randomPass" .) -}}
{{- $password_kc := (include "randomSecret" .) -}}
{{- range list .Release.Namespace .Values.namespaces.keycloak }}
kind: Secret
apiVersion: v1
metadata:
    name: kc-secrets
    namespace: {{ . }}
data:
    KEYCLOAK_GLOBAL_CLIENT_SECRET: {{ $client_secret }}
    KEYCLOAK_ADMIN_PASSWORD: {{ $password_kc }}
type: Obscure
---
{{- end }}
kind: Secret
apiVersion: v1
metadata:
    name: new-kc-secrets
    namespace: {{ .Values.namespaces.keycloak }}
    annotations:
        helm.sh/hook: pre-upgrade
        helm.sh/hook-weight: "-4"
        helm.sh/hook-delete-policy: hook-succeeded
data:
    NEW_KEYCLOAK_GLOBAL_CLIENT_SECRET: {{ $client_secret }}
    NEW_KEYCLOAK_ADMIN_PASSWORD: {{ $password_kc }}
type: Obscure
