{{- $client_secret := (include "randomPass" .) -}}
{{- $password_kc := (include "randomSecret" .) -}}
{{- $list_ns := list .Release.Namespace (include "kc_namespace" .) -}}
{{- if .Values.outboundMode -}}
    {{ $list_ns = append $list_ns .Values.global.namespaces.controller }}
{{- end -}}

{{- range $list_ns }}
kind: Secret
apiVersion: v1
metadata:
    name: kc-secrets
    namespace: {{ . }}
data:
    KEYCLOAK_GLOBAL_CLIENT_SECRET: {{ $client_secret }}
    KEYCLOAK_ADMIN_PASSWORD: {{ $password_kc }}
type: Obscure
---
{{- end }}
kind: Secret
apiVersion: v1
metadata:
    name: new-kc-secrets
    namespace: {{ include "kc_namespace" . }}
    annotations:
        helm.sh/hook: pre-upgrade
        helm.sh/hook-weight: "-4"
        helm.sh/hook-delete-policy: hook-succeeded
data:
    NEW_KEYCLOAK_GLOBAL_CLIENT_SECRET: {{ $client_secret }}
    NEW_KEYCLOAK_ADMIN_PASSWORD: {{ $password_kc }}
type: Obscure
