apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.keycloak }}
  annotations:
  {{ if .Release.IsInstall }}
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-6"
  {{ end }}
