apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-realm-init
  namespace: {{ .Values.namespaces.keycloak }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "3"
spec:
  template:
    metadata:
      name: "{{.Release.Name}}"
    spec:
      restartPolicy: Never
      containers:
        - name: post-install-job
          image: "python:3.12.1-slim-bullseye"
          command: ["/bin/sh", "-c", "pip install requests && python3 /scripts/setup_realm.py" ]
          env:
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kc-secrets
                  key: KEYCLOAK_ADMIN_PASSWORD
            - name: CERT_CRT
              value: /scripts/certs/tls.crt
            - name: CERT_KEY
              value: /scripts/certs/tls.key
          envFrom:
          - configMapRef:
              name: keycloak-config
          volumeMounts:
            - name: config
              mountPath: /scripts/
            - name: tls
              mountPath: /scripts/certs/
      volumes:
        - name: config
          configMap:
            name: keycloak-start-config
            items:
            - key: setup_realm.py
              path: setup_realm.py
        - name: tls
          secret:
            secretName: tls
