apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keycloak-role
  namespace: {{ include "kc_namespace" . }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keycloak-role-binding
  namespace: {{ include "kc_namespace" . }}
subjects:
  - kind: ServiceAccount
    namespace: {{ include "kc_namespace" . }}
    name: k8s-keycloak-handler
roleRef:
  kind: Role
  name: keycloak-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-keycloak-handler
  namespace: {{ include "kc_namespace" . }}
