apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-realm-init
  namespace: {{ .Values.namespaces.keycloak }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "3"
    {{ template "defaultAnnotations" . }}
spec:
  template:
    metadata:
      name: "{{.Release.Name}}"
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      restartPolicy: Never
      containers:
        - name: post-install-job
          image: "ghcr.io/aridhia-open-source/keycloak_initializer:{{ .Chart.AppVersion }}"
          command: ["/bin/sh", "-c", "python3 /scripts/setup_realm.py" ]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          env:
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kc-secrets
                  key: KEYCLOAK_ADMIN_PASSWORD
          envFrom:
          - configMapRef:
              name: keycloak-config
