apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: {{ .Values.namespaces.keycloak }}
spec:
  ports:
    - port: 80
      name: http
      targetPort: 8080
      protocol: TCP
  selector:
    app: keycloak
