{{- define "kc_db_host" }}
{{- if eq .Values.db.host "db" }}
  {{- print "db." .Release.Namespace ".svc.cluster.local" | quote }}
{{- else }}
  {{- .Values.db.host }}
{{- end }}
{{- end }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: {{ include "kc_namespace" . }}
data:
  KEYCLOAK_ADMIN: admin
  KC_DB_URL_HOST: {{ include "kc_db_host" . }}
  KC_DB: postgres
  KC_DB_URL_PORT: {{ .Values.db.port | quote }}
  KC_DB_URL_DATABASE: fn_{{ .Values.db.name }}
  KC_DB_USERNAME: {{ .Values.db.user | quote }}
  KEYCLOAK_TOKEN_LIFE: {{ int .Values.token.life | quote }}
  KEYCLOAK_NAMESPACE: {{ include "kc_namespace" . }}
  KEYCLOAK_HOSTNAME: {{ .Values.host }}
  # PROXY_ADDRESS_FORWARDING: true
---
{{- $list_ns := list .Release.Namespace -}}
{{- if .Values.outboundMode -}}
    {{ $list_ns = append $list_ns .Values.global.namespaces.controller }}
{{- end -}}

{{- range $list_ns }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: {{ . }}
data:
  KEYCLOAK_ADMIN: admin
  KC_DB_URL_HOST: {{ include "kc_db_host" . }}
  KC_DB_USERNAME: {{ .Values.db.user | quote }}
---
{{- end }}
