{{- $client_secret := (include "randomPass" .) -}}
{{- $password_kc := (include "randomSecret" .) -}}
{{- range list .Release.Namespace .Values.namespaces.keycloak }}
kind: Secret
apiVersion: v1
metadata:
    name: kc-secrets
    namespace: {{ . }}
data:
    KEYCLOAK_GLOBAL_CLIENT_SECRET: {{ $client_secret }}
    KEYCLOAK_ADMIN_PASSWORD: {{ $password_kc }}
    {{ if $.Values.db.password }}
    KC_DB_PASSWORD: {{ $.Values.db.password | b64enc | quote }}
    {{- end }}
type: Obscure
---
{{- end }}
