apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-start-config
  namespace: {{ .Values.namespaces.keycloak }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-5"
    "helm.sh/resource-policy": keep
data:
  config.json: |-
{{ .Files.Get "scripts/realms.json" | indent 4 }}
  setup_realm.py: |-
{{ .Files.Get "scripts/job_init.py" | indent 4 }}
  init_credentials.py: |-
{{ .Files.Get "scripts/init_credentials.py" | indent 4 }}
  quarkus.properties: |-
    quarkus.transaction-manager.enable-recovery=true
  dbinit.sh: |-
    apk --update add postgresql-client
    psql -d postgres -U $PGUSER -tc "SELECT 1 FROM pg_database WHERE datname = '$NEW_DB'" | \
    grep -q 1 || psql -d postgres -U $PGUSER -c "CREATE DATABASE $NEW_DB"
