apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.keycloak }}
  {{- if .Release.IsInstall }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-6"
    {{ template "defaultAnnotations" . }}
  {{- end }}
