apiVersion: v1
kind: Namespace
metadata:
  name: {{ index .Values "ingress-nginx" "namespaceOverride" }}
  {{- if .Release.IsInstall }}
  labels:
    {{ template "defaultLabels" . }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-6"
    {{ template "defaultAnnotations" . }}
  {{- end }}
