apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.nginx }}
  {{- if .Release.IsInstall }}
  annotations:
    helm.sh/hook: pre-install
    {{ template "defaultAnnotations" . }}
  {{- end }}
