{{- define "imagePullSecret" }}
{{- $content := "" -}}
  {{- range $v := .Values.registries -}}
    {{ if .secret }}
      {{ $sec := lookup "v1" "Secret" $.Release.Namespace .secret.name | default dict }}
      {{ if $sec }}
        {{ $username := (index $sec.data .secret.userKey) | b64dec | trim }}
        {{ $password := (index $sec.data .secret.passKey) | b64dec | trim }}
        {{- $content = (printf "%s\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}," $content $v.url $username $password "" (printf "%s:%s" $username $password | b64enc)) -}}
      {{ end }}
    {{- else }}
      {{- $content = (printf "%s\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}," $content $v.url $v.username $v.password $v.email (printf "%s:%s" $v.username $v.password | b64enc)) -}}
    {{- end }}
  {{- end }}
  .dockerconfigjson: {{ printf "{\"auths\":{ %s }}" (trimSuffix "," $content) | b64enc }}
{{- end }}

{{- range list .Release.Namespace .Values.namespaces.tasks .Values.namespaces.keycloak -}}
kind: Secret
apiVersion: v1
metadata:
  name: regcred
  namespace: {{ . }}
data:
  {{ template "imagePullSecret" $ }}
type: kubernetes.io/dockerconfigjson
---
{{- end -}}
