{{ if not .Values.local_development }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: certibot-renewer
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "0 11 * */{{ div .Values.certs.frequency 30 }} 1"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 60
      backoffLimit: 3
      template:
        spec:
          serviceAccountName: secret-cert-handler
          containers:
          - name: certibot-renewer
            image: ghcr.io/aridhia-open-source/federated_node_certificate:{{ .Chart.AppVersion }}
            imagePullPolicy: {{ .Values.pullPolicy }}
            {{- include "nonRootSC" . | indent 12 }}
            env:
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: KEYCLOAK_NAMESPACE
              value: {{ .Values.namespaces.keycloak }}
            - name: NGINX_NAMESPACE
              value: {{ .Values.namespaces.nginx }}
            - name: DOMAIN
              value: {{ .Values.certs.domain }}
            - name: SSL_SECRET_NAME
              value: {{ .Values.ingress.tls.secretName | default "tls"}}
            envFrom:
            - configMapRef:
                name: renew-cert-configmap
            - secretRef:
                {{- if .Values.certs.azure }}
                name: {{ .Values.certs.azure.sp_certificate }}
                {{- else if .Values.certs.aws }}
                name: {{ .Values.certs.aws.sp_certificate }}
                {{- end }}
            command:
            - /bin/sh
            - -c
            {{- if .Values.certs.azure }}
            - /app/scripts/azure.sh
            {{- else if .Values.certs.aws }}
            - /app/scripts/aws.sh
            {{- end }}
          restartPolicy: Never
          imagePullSecrets:
            - name: {{ .Values.imagePullSecrets }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: renew-cert-configmap
  namespace: {{ .Release.Namespace }}
data:
  EMAIL_CERT: {{ .Values.certs.azure.email }}
{{ end }}
