{{ if not .Values.local_development }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-role
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: secret-cert-handler
roleRef:
  kind: ClusterRole
  name: cert-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-cert-handler
  namespace: {{ .Release.Namespace }}
{{ end }}
