apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: shared-results
{{- if .Values.storage.local }}
provisioner: Local
volumeBindingMode: WaitForFirstConsumer
{{- else if .Values.storage.azure }}
provisioner: disk.csi.azure.com
parameters:
  skuname: Premium_LRS
volumeBindingMode: WaitForFirstConsumer
{{- else if .Values.storage.nfs }}
provisioner: {{ .Values.storage.nfs.provisioner }}
mountOptions:
  - hard
{{- end }}
{{- if and (not .Values.db.secret) }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: db-storage
{{- if .Values.storage.local }}
provisioner: Local
{{- else if .Values.storage.azure }}
provisioner: disk.csi.azure.com
parameters:
  protocol: nfs
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
mountOptions:
  - nconnect=4
  - noresvport
  - actimeo=30
  - rsize=262144
  - wsize=262144
{{- end }}
{{- end }}
