## This assumes for certain secrets to be present in the release namespace
# Basically duplicates them to the keycloak's namespace
apiVersion: v1
kind: Secret
metadata:
  name: local-db
  namespace: keycloak
data:
  password: dGVzdA==
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: test-azure
  namespace: tasks
data:
  SP_SECRET: dGVzdA==
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: test-azure
  namespace: fn-certmanager
data:
  SP_SECRET: dGVzdA==
type: Opaque
---
