"""Added ds container table

Revision ID: 00498b78378e
Revises: 48d59eae3f31
Create Date: 2025-05-02 10:08:01.125647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00498b78378e'
down_revision: Union[str, None] = '48d59eae3f31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasetcontainers',
    sa.Column('all_containers', sa.Boolean(), nullable=True),
    sa.Column('use', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('container_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # The all_containers has a default here to help legacy datasets
    # and minimize impact
    op.execute("UPDATE datasetcontainers SET all_containers=TRUE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datasetcontainers')
    # ### end Alembic commands ###
