"""sync columns

Revision ID: 04beb33ef4cb
Revises: 941b3c7aa098
Create Date: 2026-03-11 13:43:54.879880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04beb33ef4cb'
down_revision: Union[str, None] = '941b3c7aa098'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE tasks SET status='scheduled' WHERE status IS NULL")
    op.alter_column('audit', 'status_code',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('audit', 'api_function',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('audit', 'event_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('containers', 'ml',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('containers', 'dashboard',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('containers', 'registry_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('datasets', 'port',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tasks', 'description',
               existing_type=sa.VARCHAR(length=4096),
               nullable=False)
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'dataset_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'dataset_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('tasks', 'description',
               existing_type=sa.VARCHAR(length=4096),
               nullable=True)
    op.alter_column('datasets', 'port',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('containers', 'registry_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('containers', 'dashboard',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('containers', 'ml',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('audit', 'event_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit', 'api_function',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('audit', 'status_code',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
