"""schedule column

Revision ID: 1e79125ff686
Revises: 50181f0b508c
Create Date: 2025-12-10 15:22:48.030228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e79125ff686'
down_revision: Union[str, None] = '50181f0b508c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('schedule', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'schedule')
    # ### end Alembic commands ###
