"""k8s async migration sync

Revision ID: 4a2d55fd20a8
Revises: 5446dee31bf4
Create Date: 2026-03-17 14:04:53.268769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a2d55fd20a8'
down_revision: Union[str, None] = '5446dee31bf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Postgres or alembic can set nullable to false and set a default. So we go
    # the long way around
    op.add_column('tasks', sa.Column('status', sa.String(length=256), nullable=True))
    op.execute("UPDATE tasks SET status = 'pending'")
    op.alter_column('tasks', 'status', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'status')
    # ### end Alembic commands ###
