"""Added active column on registries

Revision ID: b4ce486e95bd
Revises: 48d59eae3f31
Create Date: 2025-05-16 13:30:05.710379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4ce486e95bd'
down_revision: Union[str, None] = '48d59eae3f31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datasetcontainers')
    op.add_column('registries', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registries', 'active')
    op.create_table('datasetcontainers',
    sa.Column('all', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('container_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], name='datasetcontainers_container_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name='datasetcontainers_dataset_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='datasetcontainers_pkey')
    )
    # ### end Alembic commands ###
