"""Rename containers to whitelisted_images

The table holds image allow-list entries, not containers: a row is
(registry_id, name, tag?, sha?) where no tag and no sha allows every version, a tag allows
that tag, and a sha pins that digest.

Revision ID: c4f7b1e29a83
Revises: f1e2d3c4b5a6
Create Date: 2026-08-17 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op


revision: str = 'c4f7b1e29a83'
down_revision: Union[str, None] = 'f1e2d3c4b5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _rename_constraint(table: str, old: str, new: str) -> None:
    """
    RENAME CONSTRAINT has no IF EXISTS, and this name was auto-generated by Postgres
    rather than declared, so guard on the catalogue.
    """
    op.execute(f"""
        DO $$ BEGIN
            IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = '{old}') THEN
                ALTER TABLE {table} RENAME CONSTRAINT {old} TO {new};
            END IF;
        END $$;
    """)


def upgrade() -> None:
    op.rename_table('containers', 'whitelisted_images')
    op.execute('ALTER INDEX IF EXISTS containers_pkey RENAME TO whitelisted_images_pkey')
    _rename_constraint(
        'whitelisted_images', 'containers_registry_id_fkey', 'whitelisted_images_registry_id_fkey'
    )


def downgrade() -> None:
    _rename_constraint(
        'whitelisted_images', 'whitelisted_images_registry_id_fkey', 'containers_registry_id_fkey'
    )
    op.execute('ALTER INDEX IF EXISTS whitelisted_images_pkey RENAME TO containers_pkey')
    op.rename_table('whitelisted_images', 'containers')
