"""Task orchestration schema

Renames repositories -> trigger_repositories, extends tasks with trigger, execution,
results and review columns.

Additive throughout: no existing row is rewritten, and every new column is nullable or
has a server default.

Revision ID: e7a4c9b21d38
Revises: c4f7b1e29a83
Create Date: 2026-08-17 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e7a4c9b21d38'
down_revision: Union[str, None] = 'c4f7b1e29a83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _rename_constraint(table: str, old: str, new: str) -> None:
    """
    RENAME CONSTRAINT has no IF EXISTS, and these names were auto-generated by Postgres
    rather than declared, so guard on the catalogue.
    """
    op.execute(f"""
        DO $$ BEGIN
            IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = '{old}') THEN
                ALTER TABLE {table} RENAME CONSTRAINT {old} TO {new};
            END IF;
        END $$;
    """)


def upgrade() -> None:
    op.rename_table('repositories', 'trigger_repositories')
    op.execute('ALTER INDEX IF EXISTS repositories_pkey RENAME TO trigger_repositories_pkey')
    _rename_constraint('trigger_repositories', 'uq_repositories_uri', 'uq_trigger_repositories_uri')
    _rename_constraint(
        'trigger_repositories', 'repositories_dataset_id_fkey', 'trigger_repositories_dataset_id_fkey'
    )

    op.alter_column('pull_requests', 'repository_id', new_column_name='trigger_repository_id')
    _rename_constraint(
        'pull_requests', 'pull_requests_repository_id_fkey', 'pull_requests_trigger_repository_id_fkey'
    )
    op.drop_index('ix_pull_requests_status', table_name='pull_requests')
    op.create_index(
        'ix_pull_requests_status', 'pull_requests', ['trigger_repository_id', 'status']
    )

    op.add_column(
        'trigger_repositories',
        sa.Column('created_at', sa.DateTime(timezone=False), server_default=sa.func.now()),
    )
    op.add_column(
        'trigger_repositories', sa.Column('updated_at', sa.DateTime(timezone=False), nullable=True)
    )

    op.add_column('tasks', sa.Column('trigger_source', sa.String(length=16), nullable=False, server_default='API'))
    op.add_column('tasks', sa.Column('pr_repository_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('pr_number', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('request_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('dagster_run_id', sa.String(length=64), nullable=True))
    op.add_column('tasks', sa.Column('started_at', sa.DateTime(timezone=False), nullable=True))
    op.add_column('tasks', sa.Column('completed_at', sa.DateTime(timezone=False), nullable=True))
    op.add_column('tasks', sa.Column('exit_code', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('reason', sa.String(length=256), nullable=True))
    op.add_column('tasks', sa.Column('artifact_key', sa.String(length=512), nullable=True))
    op.add_column('tasks', sa.Column('params', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('tasks', sa.Column('reviewed_by', sa.String(length=256), nullable=True))
    op.add_column('tasks', sa.Column('reviewed_at', sa.DateTime(timezone=False), nullable=True))

    op.create_unique_constraint('uq_tasks_dagster_run_id', 'tasks', ['dagster_run_id'])
    op.create_foreign_key(
        'fk_tasks_request', 'tasks', 'requests', ['request_id'], ['id'], ondelete='SET NULL'
    )
    op.create_foreign_key(
        'fk_tasks_pull_request', 'tasks', 'pull_requests',
        ['pr_repository_id', 'pr_number'], ['trigger_repository_id', 'number'],
        ondelete='SET NULL',
    )
    # Not tied to trigger_source: the FK above nulls these columns when a repository is
    # deleted, which a tied constraint would reject.
    op.create_check_constraint(
        'ck_tasks_pr_both_or_neither', 'tasks',
        '(pr_repository_id IS NULL) = (pr_number IS NULL)',
    )
    op.create_index('ix_tasks_dataset_status', 'tasks', ['dataset_id', 'status'])
    op.create_index('ix_tasks_requested_by', 'tasks', ['requested_by'])
    op.create_index('ix_tasks_trigger_source_status', 'tasks', ['trigger_source', 'status'])
    op.create_index('ix_tasks_pull_request', 'tasks', ['pr_repository_id', 'pr_number'])


def downgrade() -> None:
    op.drop_index('ix_tasks_pull_request', table_name='tasks')
    op.drop_index('ix_tasks_trigger_source_status', table_name='tasks')
    op.drop_index('ix_tasks_requested_by', table_name='tasks')
    op.drop_index('ix_tasks_dataset_status', table_name='tasks')
    op.drop_constraint('ck_tasks_pr_both_or_neither', 'tasks', type_='check')
    op.drop_constraint('fk_tasks_pull_request', 'tasks', type_='foreignkey')
    op.drop_constraint('fk_tasks_request', 'tasks', type_='foreignkey')
    op.drop_constraint('uq_tasks_dagster_run_id', 'tasks', type_='unique')
    for column in (
        'reviewed_at', 'reviewed_by', 'params', 'artifact_key', 'reason', 'exit_code',
        'completed_at', 'started_at', 'dagster_run_id', 'request_id', 'pr_number',
        'pr_repository_id', 'trigger_source',
    ):
        op.drop_column('tasks', column)

    op.drop_column('trigger_repositories', 'updated_at')
    op.drop_column('trigger_repositories', 'created_at')

    op.drop_index('ix_pull_requests_status', table_name='pull_requests')
    _rename_constraint(
        'pull_requests', 'pull_requests_trigger_repository_id_fkey', 'pull_requests_repository_id_fkey'
    )
    op.alter_column('pull_requests', 'trigger_repository_id', new_column_name='repository_id')
    op.create_index('ix_pull_requests_status', 'pull_requests', ['repository_id', 'status'])

    _rename_constraint(
        'trigger_repositories', 'trigger_repositories_dataset_id_fkey', 'repositories_dataset_id_fkey'
    )
    _rename_constraint('trigger_repositories', 'uq_trigger_repositories_uri', 'uq_repositories_uri')
    op.execute('ALTER INDEX IF EXISTS trigger_repositories_pkey RENAME TO repositories_pkey')
    op.rename_table('trigger_repositories', 'repositories')
