{{ if .Values.storage.azure }}
{{ if .Values.storage.azure.storageAccountName and .Values.storage.azure.storageAccountKey }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.storage.azure.secretName | default "azure-storage-secret" }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  azurestorageaccountname: {{ .Values.storage.azure.storageAccountName | b64enc }}
  azurestorageaccountkey: {{ .Values.storage.azure.storageAccountKey | b64enc }}
{{ end }}
{{ end }}
