kind: Secret
apiVersion: v1
metadata:
  name: backend-secrets
  namespace: {{ .Values.namespace | default "default" }}
type: Opaque
data:
    ACR_ACCESS_TOKEN: {{ .Values.federatedNode.acr_access_token }}
