apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Values.namespace | default "default" }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.federatedNode.port | default 5000 }}
      name: http
      targetPort: {{ .Values.federatedNode.port | default 5000 }}
      protocol: TCP
  selector:
    app: flask
