{{- $db_pass := .Values.db.password | default "password123" -}}
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
    ACR_USERNAME: {{ .Values.federatedNode.acr_username | b64enc | quote }}
    ACR_PASSWORD: {{ .Values.federatedNode.acr_password | b64enc | quote }}
    PGDATABASE: {{ $db_pass | b64enc | quote }}
