kind: Secret
apiVersion: v1
metadata:
  name: backend-secrets
  namespace: {{ .Values.namespace | default "default" }}
type: Opaque
data:
    ACR_USERNAME: {{ .Values.federatedNode.acr_username | b64enc | quote }}
    ACR_PASSWORD: {{ .Values.federatedNode.acr_password | b64enc | quote }}
