apiVersion: v1
kind: PersistentVolume
metadata:
  name: flask-results-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Mi
  # This should be changed to some more reliable destination
  hostPath:
    path: /data/flask/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-results-pv-volclaim
spec:
  resources:
    requests:
      storage: 100Mi
  # This should be changed to some more reliable destination
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
