apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Mi
  # This should be changed to some more reliable destination
  hostPath:
    path: /data/db/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-volclaim
spec:
  resources:
    requests:
      storage: 100Mi
  # This should be changed to some more reliable destination
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
