apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: {{ .Values.namespace | default "default" }}
spec:
  type: NodePort
  ports:
    - port: 5432
      name: pgport
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres
