{{ if and (not .Values.db.secret) (not .Values.db.configMap) }}
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 5432
      name: pgport
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres
{{ end }}
