apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: flask
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      initContainers:
        - name: db-migrations
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command: ["/bin/sh"]
          workingDir: /
          args:
            [
              "-c",
              'python -m alembic upgrade head',
            ]
          envFrom:
            - configMapRef:
                name: backend-configmap
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          name: flask-app
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            limits:
              memory: 200Mi
              cpu: 100m
          ports:
            - name: http
              containerPort: {{ .Values.federatedNode.port | default 5000 }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health_check
              port: http
            initialDelaySeconds: 30
            periodSeconds: 180
            timeoutSeconds: 30
          livenessProbe:
            httpGet:
              path: /health_check
              port: http
            initialDelaySeconds: 10
            periodSeconds: 180
            timeoutSeconds: 30
          envFrom:
            - configMapRef:
                name: backend-configmap
      imagePullSecrets:
        - name: regcred
