{{- $client_secret := randAlphaNum 24 | b64enc | quote -}}
{{- $password_kc := randAlphaNum 24 | b64enc | quote -}}
kind: Secret
apiVersion: v1
metadata:
    name: kc-secrets
    namespace: {{ .Values.namespaces.keycloak }}
data:
    KEYCLOAK_GLOBAL_CLIENT_SECRET: {{ $client_secret }}
    KEYCLOAK_ADMIN_PASSWORD: {{ $password_kc }}
type: Obscure
---
kind: Secret
apiVersion: v1
metadata:
    name: kc-secrets
    namespace: {{ .Release.Namespace }}
data:
    KEYCLOAK_GLOBAL_CLIENT_SECRET: {{ $client_secret }}
    KEYCLOAK_ADMIN_PASSWORD: {{ $password_kc }}
type: Obscure
