{{- $client_secret := (include "randomPass" .) -}}
{{- $password_kc := (include "randomSecret" .) -}}
{{- $db_pass := .Values.db.password | default "password123" -}}
{{- range list .Release.Namespace .Values.namespaces.keycloak }}
kind: Secret
apiVersion: v1
metadata:
    name: kc-secrets
    namespace: {{ . }}
data:
    KEYCLOAK_GLOBAL_CLIENT_SECRET: {{ $client_secret }}
    KEYCLOAK_ADMIN_PASSWORD: {{ $password_kc }}
    KC_DB_PASSWORD: {{ $db_pass | b64enc | quote }}
type: Obscure
---
{{- end }}
