apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-start-config
  namespace: keycloak
data:
  config.json: |-
{{ .Files.Get "scripts/realms.json" | indent 4 }}
  setup_realm.py: |-
{{ .Files.Get "scripts/job_init.py" | indent 4 }}
