{{- define "client_secret" -}}
{{- randAlphaNum 24 | b64enc | quote -}}
{{- end -}}
{{- define "password_kc" -}}
{{- randAlphaNum 24 | b64enc | quote -}}
{{- end -}}
kind: Secret
apiVersion: v1
metadata:
    name: kc-secrets
    namespace: keycloak
data:
    KEYCLOAK_GLOBAL_CLIENT_SECRET: {{ include "client_secret" .}}
    KEYCLOAK_ADMIN_PASSWORD: {{ include "password_kc" .}}
type: Obscure
---
kind: Secret
apiVersion: v1
metadata:
    name: kc-secrets
    namespace: default
data:
    KEYCLOAK_GLOBAL_CLIENT_SECRET: {{ include "client_secret" .}}
    KEYCLOAK_ADMIN_PASSWORD: {{ include "password_kc" .}}
type: Obscure
