apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
  namespace: {{ .Values.namespaces.keycloak }}
  labels:
    app: keycloak
spec:
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - image: quay.io/keycloak/keycloak:23.0.4
          args: [
            "start-dev",
            "--import-realm",
            "--features=preview",
            "--http-enabled=true",
            "--hostname-strict=false",
            "--hostname-strict-https=false"
          ]
          name: keycloak
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
          envFrom:
          - configMapRef:
              name: keycloak-config
          env:
            - name: KEYCLOAK_SECRET
              valueFrom:
                secretKeyRef:
                  name: kc-secrets
                  key: KEYCLOAK_GLOBAL_CLIENT_SECRET
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kc-secrets
                  key: KEYCLOAK_ADMIN_PASSWORD
          envFrom:
          - configMapRef:
              name: keycloak-config
          volumeMounts:
            - name: config
              mountPath: /opt/keycloak/data/import/
      volumes:
        - name: config
          configMap:
            name: keycloak-start-config
            items:
            - key: config.json
              path: config.json
