apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: {{ .Values.namespaces.keycloak }}
data:
  KEYCLOAK_ADMIN: admin
  KC_DB_URL_HOST: "db.{{ .Release.Namespace }}.svc.cluster.local"
  KC_DB: postgres
  KC_DB_URL_PORT: "5432"
  KC_DB_URL_DATABASE: {{ .Values.db.name | default "fndb" | quote }}
  KC_DB_USERNAME: {{ .Values.db.user | default "admin" | quote }}
  KC_DB_PASSWORD: {{ .Values.db.password | default "password123" | quote }}
  KEYCLOAK_TOKEN_LIFE: {{ .Values.token.life | default 2592000 | quote }}
  KEYCLOAK_NAMESPACE: {{ .Values.namespaces.keycloak }}
  # PROXY_ADDRESS_FORWARDING: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: {{ .Release.Namespace }}

data:
  KEYCLOAK_ADMIN: admin
