apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: {{ .Values.namespaces.keycloak }}
spec:
  ports:
    - port: 8080
      name: http
      targetPort: 8080
      protocol: TCP
  selector:
    app: keycloak
---
kind: Service
apiVersion: v1
metadata:
  name: keycloak
  namespace: {{ .Release.Namespace }}
spec:
  type: ExternalName
  externalName: keycloak.{{ .Values.namespaces.keycloak }}
