{{- $client_secret := randAlphaNum 24 | b64enc | quote -}}
{{- $password_kc := randAlphaNum 24 | b64enc | quote -}}
<<<<<<< HEAD
{{- range list .Release.Namespace .Values.namespaces.keycloak }}
=======
>>>>>>> main
kind: Secret
apiVersion: v1
metadata:
    name: kc-secrets
<<<<<<< HEAD
    namespace: {{.}}
=======
    namespace: {{ .Values.namespaces.keycloak }}
>>>>>>> main
data:
    KEYCLOAK_GLOBAL_CLIENT_SECRET: {{ $client_secret }}
    KEYCLOAK_ADMIN_PASSWORD: {{ $password_kc }}
type: Obscure
---
<<<<<<< HEAD
{{- end }}
=======
kind: Secret
apiVersion: v1
metadata:
    name: kc-secrets
    namespace: {{ .Release.Namespace }}
data:
    KEYCLOAK_GLOBAL_CLIENT_SECRET: {{ $client_secret }}
    KEYCLOAK_ADMIN_PASSWORD: {{ $password_kc }}
type: Obscure
>>>>>>> main
