kind: Secret
apiVersion: v1
metadata:
  name: regcred
  namespace: {{ .Values.namespace | default "default" }}
data:
  .dockerconfigjson: {{ .Values.dockerjsonconfig }}
type: kubernetes.io/dockerconfigjson
