kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: shared-results
{{ if .Values.storage.local }}
provisioner: Local
volumeBindingMode: WaitForFirstConsumer
{{- else if .Values.storage.azure -}}
provisioner: kubernetes.io/azure-file
parameters:
  storageAccount: {{ .Values.storage.azure.storageAccountName }}
{{- else if .Values.storage.nfs -}}
provisioner: {{ .Values.storage.nfs.provisioner -}}
parameters:
  server: {{ .Values.storage.nfs.url -}}
  path: {{ .Values.storage.nfs.path -}}
  readOnly: "false"
{{- end -}}
