version: '3'
name: federated_node_dev
services:
  db:
    image: 'postgres:13-alpine'
    environment:
      POSTGRES_DB: test_app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test_app
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  app:
    container_name: flask_app_dev
    image: federated_node_app_dev
    build:
      context: .
      dockerfile: build/Dockerfile
      no_cache: true
    links:
      - db
    depends_on:
      - db
    ports:
      - 5000:5000
    working_dir: /
    volumes:
      - ./app:/app
    environment:
      PGHOST: db
      PGDATABASE: test_app
      PGPORT: 5432
      PGUSER: admin
      PGPASSWORD: test_app
volumes:
  data:
