version: '3'
name: federated_node_tests
services:
  db:
    image: 'postgres:13-alpine'
    environment:
      POSTGRES_DB: test_app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test_app
    volumes:
      - data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
  keycloak:
    container_name: keycloak_test
    image: quay.io/keycloak/keycloak:23.0.4
    command: [
      "start-dev",
      "--import-realm",
      "--features=preview",
      "--http-enabled=true",
      "--hostname-strict=false",
      "--hostname-strict-https=false"
    ]
    depends_on:
      - db
    environment:
      KC_DB_URL_HOST: ${PGHOST}
      KC_DB: postgres
      KC_DB_URL_PORT: ${PGPORT}
      KC_DB_URL_DATABASE: ${PGDATABASE}
      KC_DB_USERNAME: ${PGUSER}
      KC_DB_PASSWORD: ${PGPASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_SECRET: ${KEYCLOAK_SECRET}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - ../k8s/federated_node/scripts/realms.json:/opt/keycloak/data/import/realms.json
  kc_init:
    image: python:3.12.1-slim-bullseye
    container_name: keycloak_test_initializer
    depends_on:
      - keycloak
    command: ["/bin/sh", "-c", "pip install requests && python3 /scripts/setup_realm.py" ]
    environment:
      KEYCLOAK_ADMIN_PASSWORD:
      KEYCLOAK_ADMIN:
      KEYCLOAK_URL:
    volumes:
      - ../k8s/federated_node/scripts/job_init.py:/scripts/setup_realm.py
  app:
    container_name: flask_app_test
    image: federated_node_app_test
    build:
      context: .
      dockerfile: build/test.Dockerfile
    links:
      - db
    depends_on:
      kc_init:
        condition: service_completed_successfully
    volumes:
      - ./tests:/app/tests
      - ./app:/app/app
    environment:
      PGHOST:
      PGDATABASE:
      PGPORT:
      PGUSER:
      PGPASSWORD:
      ACR_URL:
      PYTHONPATH: /app
      KEYCLOAK_ADMIN:
      KEYCLOAK_SECRET:
      KEYCLOAK_ADMIN_PASSWORD:
      KEYCLOAK_URL:
volumes:
  data:
