version: '3'
name: federated_node_tests
services:
  db:
    image: 'postgres:13-alpine'
    environment:
      POSTGRES_DB: test_app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test_app
    volumes:
      - data:/var/lib/postgresql/data
  app:
    container_name: flask_app_test
    image: federated_node_app_test
    build:
      context: .
      dockerfile: build/test.Dockerfile
      no_cache: true
    links:
      - db
    entrypoint: ["/bin/bash"]

    depends_on:
      - db
    volumes:
      - ./tests:/app/tests
      - ./app:/app/app
    environment:
      PGHOST: db
      PGDATABASE: test_app
      PGPORT: 5432
      PGUSER: admin
      PGPASSWORD: test_app
      PYTHONPATH: /app
volumes:
  data:
