# Only rendered if SSL certificates are needed
{{- if (index .Values "cert-manager" "enabled") }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: www
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: post-install, post-upgrade
spec:
  secretName: {{ .Values.tls.secretName }}
  dnsNames:
    - {{ .Values.host }}
  issuerRef:
    name: ssl-issuer
    kind: ClusterIssuer
  privateKey:
    rotationPolicy: {{ .Values.certs.rotationPolicy | default "Never" }}
{{- end }}
