# Only rendered if SSL certificates are needed
{{- if (index .Values "cert-manager" "enabled") }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: www
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: post-install, post-upgrade
spec:
  secretName: {{ .Values.ingress.tls.secretName }}
  revisionHistoryLimit: 1
  privateKey:
    rotationPolicy: Always
  commonName: {{ .Values.ingress.host }}
  dnsNames:
    - {{ .Values.ingress.host }}
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: ssl-issuer
    kind: ClusterIssuer
{{- end }}
