# Only rendered if SSL certificates are needed
{{- if .Values.certmanager.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ssl-issuer
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.local_development }}
  selfSigned: {}
  {{- else if .Values.ingress.on_aks }}
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ $sec.data.EMAIL_CERT | b64dec }}
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        azureDNS:
          clientSecretSecretRef:
            name: azuredns-config
            key: client-secret
          resourceGroupName: {{ $sec.data.RG_NAME | b64dec }}
          subscriptionID: {{ $sec.data.SUBSCRIPTION_ID | b64dec }}
          hostedZoneName: {{ .Values.ingress.host }}
          environment: AzurePublicCloud
          clientID: {{ $sec.data.CLIENT_ID | b64dec }}
  {{- else if .Values.ingress.on_eks }}
  {{- $sec := lookup "v1" "Secret" $.Release.Namespace .Values.certs.aws | default dict }}
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ $sec.data.EMAIL_CERT | b64dec }}
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - dns01:
        route53:
          region: {{ $sec.data.REGION | b64dec }}
          role: arn:aws:iam::{{ $sec.data.ACCOUNT_ID | b64dec }}:role/{{ $sec.data.ROLE_NAME | b64dec }}
          auth:
            kubernetes:
              serviceAccountRef:
                name: cert-manager-acme-dns01-route53
  {{- end }}
{{- end }}
