apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'federatednode'
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Aridhia-Open-Source/PHEMS_federated_node'
    path: k8s/federated-node
    targetRevision: main
    helm:
      # paste the custom helm values content in here
      values: |
        registries:
          - url:
            secret:
              name:
              userKey:
              passKey:
    chart: federated-node
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated: {}
