apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-internal
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres:13-alpine
          name: db-internal
          env:
            - name: POSTGRES_DB
              value: "test_app"
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "test_app"
