apiVersion: apps/v1
kind: Deployment
metadata:
  name: testdb
  labels:
    app: testdb
spec:
  selector:
    matchLabels:
      app: testdb
  template:
    metadata:
      labels:
        app: testdb
    spec:
      containers:
        - image: postgres:13-alpine
          name: testdb
          env:
            - name: POSTGRES_DB
              value: "testing21"
            - name: POSTGRES_USER
              value: "user"
            - name: POSTGRES_PASSWORD
              value: "password1"
---
apiVersion: v1
kind: Service
metadata:
  name: testdb
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: testdb
