#!/usr/bin/env bash
set -euo pipefail

###############################################################################
# Helm Deployment - Sets up namespaces, secrets, and deploys Helm release
###############################################################################

source .dev.env

# Host directory backing the cluster's local PVs. cluster.sh bind-mounts it to /data
# in the kind node, which is what the chart's storage.local.* values point at. Under
# $HOME so none of this needs sudo.
FN_DATA_DIR="${FN_DATA_DIR:-$HOME/.fn/data}"

HOST_MOUNT_PATHS=(
  "$FN_DATA_DIR/db"
  "$FN_DATA_DIR/flask"
  "$FN_DATA_DIR/controller"
  "$FN_DATA_DIR/dagster/artifacts"
  "$FN_DATA_DIR/datasets"
)

echo
echo "=== Terminating tilt sessions =================================================="

if command -v tilt &> /dev/null; then
  if pgrep -f "tilt serve" > /dev/null; then
    tilt down
    echo "Terminated tilt session"
  else
    echo "No tilt sessions found"
  fi
fi

echo
echo "=== Reconciling PersistentVolumes ======================================"

if [ ! -d "$FN_DATA_DIR" ]; then
  echo "$FN_DATA_DIR does not exist - run ./scripts/cluster.sh up first, since the"
  echo "bind mount into the kind node is set when the cluster is created." >&2
  exit 1
fi

for path in "${HOST_MOUNT_PATHS[@]}"; do
  echo "mkdir $path"
  mkdir -p "$path"
  # The containers that write here run as their own uids (postgres is 70).
  chmod 777 "$path"
done

echo
echo "=== Building Docker Images(s) ========================================"

./scripts/build_all_images.sh $DOCKER_TAG

echo
echo "=== Creating Namespace ==================================================="
kubectl create namespace "$NAMESPACE" \
  --dry-run=client -o yaml | kubectl apply -f -

# The keycloak namespace is created by a chart pre-install hook, not here.

echo
echo "=== Creating externally-supplied secrets ================================="
# Only what the chart cannot invent: every database password is generated by its
# pre-install hooks and reused on every upgrade.
kubectl create secret generic github-token \
  --from-literal=GH_TOKEN="$GH_TOKEN" \
  --dry-run=client -o yaml -n "$NAMESPACE" | kubectl apply -f - -n "$NAMESPACE"

kubectl create secret generic keycloak-first-user \
  --from-literal=PASSWORD="$KEYCLOAK_FIRST_USER_PASSWORD" \
  --dry-run=client -o yaml -n "$NAMESPACE" | kubectl apply -f - -n "$NAMESPACE"

# An external Postgres has an admin password the chart cannot generate.
if [ "${POSTGRES_EXTERNAL:-false}" = "true" ]; then
  kubectl create secret generic postgres-superuser \
    --from-literal=password="${POSTGRES_PASSWORD:?POSTGRES_EXTERNAL is set, so POSTGRES_PASSWORD is required}" \
    --dry-run=client -o yaml -n "$NAMESPACE" | kubectl apply -f - -n "$NAMESPACE"
fi

echo
echo "=== Deploying Helm Release =============================================="

cd k8s/federated-node

helm upgrade \
  --install "$RELEASE_NAME" . \
  -f "$VALUES_FILE" \
  --timeout 10m \
  --namespace "$NAMESPACE"

cd - > /dev/null

kubectl config set-context \
  --current --namespace="$NAMESPACE"

echo
echo "=== Helm Deployment Complete ==========================================="
echo "Namespace: $NAMESPACE"
echo "Release: $RELEASE_NAME"
echo
echo "Chart-generated database passwords:"
kubectl get secret -n "$NAMESPACE" -l federatednode.com/generated-password=true \
  -o go-template='{{range .items}}  {{printf "%-26s" .metadata.name}}{{range $k, $v := .data}}{{$k}}={{$v | base64decode}}{{end}}{{"\n"}}{{end}}'
echo
echo "Watch pods with:"
echo "  kubectl get pods -n $NAMESPACE -w"
echo
