name: build-flask
run-name: Building flask image
on:
  push:
    branches:
      - main
      # To remove before merging
      - FN-5
  pull_request:
    branches:
      - main
jobs:
  tests:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Python Tests
        working-directory: webserver
        run: |
          make tests_ci
        env:
          PGHOST: db
          PGDATABASE: test_app
          PGPORT: 5432
          PGUSER: admin
          PGPASSWORD: test_app
          PYTHONPATH: /app
          ACR_URL: test.acr.com
          ACR_USERNAME: test
          ACR_PASSWORD: pass
          RESULTS_PATH: /tmp/results
          TASK_POD_RESULTS_PATH: /mnt/data
          KEYCLOAK_URL: http://keycloak:8080
          KEYCLOAK_ADMIN: kc_admin
          KEYCLOAK_SECRET: asdf12ad89123ocasASD129
          KEYCLOAK_ADMIN_PASSWORD: password1
          TASK_NAMESPACE: tasks
          KEYCLOAK_NAMESPACE: keycloak

      - name: Run pylint
        working-directory: webserver
        run: |
          make pylint

      - name: Run hadolint
        run: |
          make pylint
      - uses: irongut/CodeCoverageSummary@v1.3.0
        name: Code Coverage Summary Report
        with:
          filename: artifacts/coverage.xml
          fail_below_min: true
          thresholds: '60 80'
  build:
    needs: tests
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

        # Need to get an ACR where to push the image
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: webserver
          file: build/Dockerfile
          tags: federated_node_run:${{ vars.VERSION }}
          push: false
