name: Version bump
run-name: Version bump
on:
  workflow_dispatch:
    inputs:
      chartVersion:
        description: 'New Helm Chart version'
        required: true
        type: string
      appVersion:
        description: 'New tag the docker images are going to use'
        required: false
        type: string

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update Version
        working-directory: k8s/federated-node
        env:
          CHART_VERSION: ${{ inputs.chartVersion }}
          APP_VERSION: ${{ inputs.appVersion }}
        run: |
          sed -i "s/version: .*/version: ${CHART_VERSION}/" Chart.yaml

          if [[ -z "${APP_VERSION}" ]]; then
            sed -i "s/version: .*/appVersion: \"${APP_VERSION}\"/" Chart.yaml
          fi

          git add Chart.yaml
          git commit -m "Version bump to ${CHART_VERSION}"
          git push
