name: Releases

on:
  push:
    tags:
    - '*'
    # To remove before merging
    branches:
      - FN-5
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Build helm archive
      working-directory: k8s/federated-node
      run: |
        helm package . -d ../../artifacts/ --app-version ${{ vars.VERSION }}
    - name: Push to GitLab Package Artifact
      run: |
        echo ${{ secrets.HELM_TOKEN }} | helm registry login -u ${{ vars.USER_HELM }} ${{ vars.HELM_REPO }} --password-stdin
        helm push ../../artifacts/federated-node-${{ vars.VERSION }}.tgz oci://$CI_REGISTRY/aridhia/federated-node
    - name: Publish Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "artifacts/federated-node-${{ vars.VERSION }}.tgz"
        tag: ${{ vars.VERSION }}
        skipIfReleaseExists: true
