name: Releases

on:
  push:
    tags:
    - '*'
    # To remove before merging
    branches:
      - FN-5
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Build helm archive
      run: |
        helm package . -d ../../artifacts/ --app-version ${{ vars.VERSION }}
    - name: Publish Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "artifacts/*.tgz"
    - name: Push to GitLab Package Artifact
      run: |
        curl --request POST \
        --form 'chart=@federated_node-${{ vars.VERSION }}.tgz' \
        --user r-casula:${{ secrets.HELM_TOKEN }} \
        https://gitlab.com/api/v4/projects/aridhia%2Ffederated_node/packages/helm/api/devel/charts
