name: Releases

on:
  push:
    tags:
    - '*'
    # To remove before merging
    branches:
      - FN-5
  workflow_run:
    workflows:
      Build Docker Image
    types:
      completed
env:
  HELM_CHANNEL: stable

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Build helm archive
      working-directory: k8s/federated-node
      run: |
        helm package . -d ../../artifacts/ --app-version ${{ vars.VERSION }}

    - name: Set helm channel to develop for dev branches
      if: github.ref != 'refs/heads/master'
      run: echo "HELM_CHANNEL=develop" >> ${GITHUB_ENV}

    - name: Push to GitLab Package Artifact
      run: |
        curl --request POST \
          --form 'chart=@artifacts/federated-node-${{ vars.VERSION }}.tgz' \
          --user ${{ vars.USER_HELM }}:${{ secrets.HELM_TOKEN }} \
          https://gitlab.com/api/v4/projects/aridhia%2Ffederated-node/packages/helm/api/${{ env.HELM_CHANNEL }}/charts

    # - name: Push to GitLab Package Artifact
    #   run: |
    #     echo ${{ secrets.HELM_TOKEN }} | helm registry login -u ${{ vars.USER_HELM }} ${{ vars.HELM_REPO }} --password-stdin
    #     helm push artifacts/federated-node-${{ vars.VERSION }}.tgz oci://${{ vars.HELM_REPO }}/aridhia/federated-node
    - name: Publish Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "artifacts/federated-node-${{ vars.VERSION }}.tgz"
        tag: ${{ vars.VERSION }}
        skipIfReleaseExists: true
