name: Releases

on:
  push:
    tags:
    - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Build helm archive
      run: |
        helm package . -d ../../artifacts/ --app-version ${{ vars.VERSION }}
    - name: Publish Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "artifacts/*.tgz"
