name: Releases
run-name: Build and push helm chart
on:
  push:
    tags:
    - '*'
  workflow_run:
    workflows:
      Build Docker Image
    types:
      completed
env:
  HELM_CHANNEL: stable

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Build helm archive
      working-directory: k8s/federated-node
      run: |
        helm package . -d ../../artifacts/ --app-version ${{ vars.VERSION }}

    - name: Set helm channel to develop for dev branches
      if: github.ref != 'refs/heads/master'
      run: echo "HELM_CHANNEL=develop" >> ${GITHUB_ENV}

    - name: Push to GitLab Package Artifact
      run: |
        curl --request POST \
          --form 'chart=@artifacts/federated-node-${{ vars.VERSION }}.tgz' \
          --user ${{ vars.USER_HELM }}:${{ secrets.HELM_TOKEN }} \
          ${{ vars.HELM_REPO }}/helm/api/${{ env.HELM_CHANNEL }}/charts

    - name: Publish Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "artifacts/federated-node-${{ vars.VERSION }}.tgz"
        tag: ${{ vars.VERSION }}
        skipIfReleaseExists: true
